### PR TITLE
feat(trip requests): requests trips

### PR DESCRIPTION
**Pull request by James-nyagatare**
## What does this PR do?
- request, update, get trips

## Description of Task to be completed?
```
- Adds a trip requests
- Gets all requesters trips
- Gets a single requester trip
- Updates a requester trip
```
## How should this be manually tested?
- Using postman and swagger documentation

## Any background context you want to provide?
- N/A
## What are the relevant pivotal tracker stories?
- [Story](https://www.pivotaltracker.com/story/show/176153399)

## Screenshots (if appropriate)
- N/A
## Questions:
- N/A

### CODE REVIEW

**Review by unadine — COMMENTED** [review]
@James-nyagatare  can you fix these errors in UserServices.js

**Review by unadine — COMMENTED** [review]
everything else is good

**Review by Mucyo-Aime-Christian — COMMENTED** [review]
LGTM

**Comment by James-nyagatare** [comment]
@unadine I don't think there is that error anymore. you can recheck. Thanks

**Pull request merged**
